"""Deterministic alert correlation policy contracts."""

from .contracts import (
    AnchorStrength,
    AnchorTransition,
    CorrelationDecision,
    CorrelationErrorCode,
    CorrelationEvaluationContext,
    CorrelationEvaluationError,
    CorrelationEvaluationFailure,
    CorrelationEvaluationResult,
    CorrelationEvaluationSuccess,
    CorrelationFamily,
    DecisionReasonCode,
    DecisionType,
    EvaluationPhase,
    EvidenceClass,
    IncidentCorrelationView,
    NormalizedFingerprint,
)
from .engine import AlertCorrelationPolicyEngine, CorrelationEngineConfig
from .policy import (
    DEFAULT_POLICY_REGISTRY,
    POC_V1_POLICIES,
    CorrelationPolicy,
    FieldPathIdentityExtractor,
    IdentityExtractionError,
    IdentityExtractor,
    PolicyDefinitionError,
    PolicyRegistry,
)

__all__ = [
    "AlertCorrelationPolicyEngine",
    "AnchorStrength",
    "AnchorTransition",
    "CorrelationDecision",
    "CorrelationEngineConfig",
    "CorrelationErrorCode",
    "CorrelationEvaluationContext",
    "CorrelationEvaluationError",
    "CorrelationEvaluationFailure",
    "CorrelationEvaluationResult",
    "CorrelationEvaluationSuccess",
    "CorrelationFamily",
    "CorrelationPolicy",
    "DEFAULT_POLICY_REGISTRY",
    "DecisionReasonCode",
    "DecisionType",
    "EvaluationPhase",
    "EvidenceClass",
    "FieldPathIdentityExtractor",
    "IdentityExtractionError",
    "IdentityExtractor",
    "IncidentCorrelationView",
    "NormalizedFingerprint",
    "POC_V1_POLICIES",
    "PolicyDefinitionError",
    "PolicyRegistry",
]
