"""Authoritative SPEC-008 Incident-domain contracts and persistence."""

from .contracts import (
    CORRELATION_CLOSED_STATUSES,
    CORRELATION_OPEN_STATUSES,
    INCIDENT_ERROR_DISPOSITIONS,
    RCA_INITIAL_STATUS,
    EventMutationProjection,
    IncidentAuditAction,
    IncidentAuditEffect,
    IncidentAuditEntry,
    IncidentCorrelationContext,
    IncidentDomainError,
    IncidentErrorCode,
    IncidentMutationCompletion,
    IncidentMutationRequest,
    IncidentOperationReceipt,
    IncidentOperationResult,
    IncidentRecord,
    IncidentSeverity,
    IncidentStatus,
    OperationReceiptSemanticIdentity,
    event_mutation_projection,
)
from .sqlite_store import (
    DEFAULT_DATABASE_PATH,
    SCHEMA_VERSION,
    STATE_VERSION,
    SqliteIncidentStore,
)
from .manager import IncidentIdFactory, IncidentManager

__all__ = [
    "CORRELATION_CLOSED_STATUSES",
    "CORRELATION_OPEN_STATUSES",
    "EventMutationProjection",
    "DEFAULT_DATABASE_PATH",
    "INCIDENT_ERROR_DISPOSITIONS",
    "IncidentAuditAction",
    "IncidentAuditEffect",
    "IncidentAuditEntry",
    "IncidentCorrelationContext",
    "IncidentDomainError",
    "IncidentErrorCode",
    "IncidentIdFactory",
    "IncidentManager",
    "IncidentMutationCompletion",
    "IncidentMutationRequest",
    "IncidentOperationReceipt",
    "IncidentOperationResult",
    "IncidentRecord",
    "IncidentSeverity",
    "IncidentStatus",
    "OperationReceiptSemanticIdentity",
    "RCA_INITIAL_STATUS",
    "SCHEMA_VERSION",
    "STATE_VERSION",
    "SqliteIncidentStore",
    "event_mutation_projection",
]
