"""Public SPEC-013 Candidate-B Phase 1 semantic surface."""

from .contracts import (
    BoundsOmissionFacts,
    CaptureCommand,
    CapturePlan,
    CaptureFailure,
    CaptureSuccess,
    CaptureTerminalOutcome,
    CaptureTerminalKind,
    CollectionProvenance,
    EvidenceCompleteness,
    EvidenceIntegrityStatus,
    EvidenceReadiness,
    EvidenceRecoveryFacts,
    EvidenceRevision,
    EvidenceSnapshot,
    EvidenceSource,
    MaterialityEvaluationKind,
    MaterialityJudgement,
    MaterialityRequest,
    MaterialityResult,
    IncidentCaptureProjection,
    PlannedSelector,
    QueryProvenance,
    SelectorFact,
    SourceCollectionSummary,
    SourceAdapterRequest,
    SourceStatus,
    TrustedEvent,
)
from .errors import (
    DEFAULT_RETRY_DISPOSITIONS,
    EvidenceDomainError,
    EvidenceFailureKind,
    EvidenceStoreError,
    EvidenceStoreIntegrityError,
    RetryDisposition,
)
from .identity import (
    canonical_json,
    canonical_unordered_items,
    capture_command_semantic_identity,
    semantic_identity,
)
from .policy import EvidencePolicy, EvidencePolicyConfigError, load_evidence_policy
from .security import (
    build_selector_fact,
    ensure_no_ground_truth_fields,
    redact_sensitive_mapping,
    sanitize_provenance,
    validate_safe_provenance,
)
from .time_semantics import (
    CollectionWindows,
    Episode,
    LogicalWindow,
    canonical_utc,
    derive_collection_windows,
    derive_episode,
    format_utc,
)
from .sqlite_store import SCHEMA_VERSION, STORE_DOMAIN, SqliteEvidenceStore
from .capture_plan import build_capture_plan
from .trusted_core import admit_capture_plan
from .adapters import (
    LokiLogRecord,
    LokiRangeAdapter,
    LokiSourceResult,
    PrometheusRangeAdapter,
    PrometheusSampleRecord,
    PrometheusSourceResult,
)

__all__ = [
    "BoundsOmissionFacts",
    "CaptureCommand",
    "CapturePlan",
    "CaptureFailure",
    "CaptureSuccess",
    "CaptureTerminalOutcome",
    "CaptureTerminalKind",
    "CollectionProvenance",
    "CollectionWindows",
    "DEFAULT_RETRY_DISPOSITIONS",
    "Episode",
    "EvidenceCompleteness",
    "EvidenceIntegrityStatus",
    "EvidenceReadiness",
    "EvidenceRecoveryFacts",
    "EvidenceRevision",
    "EvidenceSnapshot",
    "EvidenceDomainError",
    "EvidenceFailureKind",
    "EvidenceStoreError",
    "EvidenceStoreIntegrityError",
    "EvidencePolicy",
    "EvidencePolicyConfigError",
    "EvidenceSource",
    "LogicalWindow",
    "LokiLogRecord",
    "LokiRangeAdapter",
    "LokiSourceResult",
    "IncidentCaptureProjection",
    "MaterialityEvaluationKind",
    "MaterialityJudgement",
    "MaterialityRequest",
    "MaterialityResult",
    "QueryProvenance",
    "PlannedSelector",
    "PrometheusRangeAdapter",
    "PrometheusSampleRecord",
    "PrometheusSourceResult",
    "RetryDisposition",
    "SelectorFact",
    "SourceCollectionSummary",
    "SourceAdapterRequest",
    "SourceStatus",
    "TrustedEvent",
    "SCHEMA_VERSION",
    "STORE_DOMAIN",
    "SqliteEvidenceStore",
    "build_selector_fact",
    "build_capture_plan",
    "canonical_json",
    "canonical_unordered_items",
    "canonical_utc",
    "capture_command_semantic_identity",
    "derive_collection_windows",
    "derive_episode",
    "ensure_no_ground_truth_fields",
    "format_utc",
    "load_evidence_policy",
    "redact_sensitive_mapping",
    "sanitize_provenance",
    "semantic_identity",
    "validate_safe_provenance",
    "admit_capture_plan",
]
